### ISSUE TITLE
CRAN system file error

### ISSUE THREAD

**Issue by atkinsjeff** [atkinsjeff/forestr#3]
Note from CRAN:

----
Thanks, we get:

Check: examples, Result: ERROR
  Running examples in ‘forestr-Ex.R’ failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: process_pcl
  > ### Title: Process single PCL transects.
  > ### Aliases: process_pcl
  > ### Keywords: pcl processing
  >
  > ### ** Examples
  >
  > # Link to stored, raw PCL data in .csv form
  > uva.pcl <- system.file("extdata", "UVAX_A4_01W.csv", package = "forestr")
  >
  > # Run process complete PCL transect, store output to disk
  > process_pcl(uva.pcl, marker.spacing = 10, user_height = 1.05,
  + max.vai = 8, pavd = FALSE, hist = FALSE)
  Warning in file(file, "rt") :
    file("") only supports open = "w+" and open = "w+b": using the former
  how many in base df have NA
  [1] 0
  Transect Length
  [1] -10
  Error in `$<-.data.frame`(`*tmp*`, "sky_hit", value = TRUE) :
    replacement has 1 row, data has 0
  Calls: process_pcl -> code_hits -> $<- -> $<-.data.frame
  Execution halted

And: Package has a VignetteBuilder field but no prebuilt vignette index.

Check: re-building of vignette outputs, Result: WARNING
  Error in re-building vignettes:
    ...
  Quitting from lines 47-53 (pcl-vignette.Rmd)
  Error: processing vignette ‘pcl-vignette.Rmd’ failed with diagnostics:
  replacement has 1 row, data has 0
  Execution halted

Please fix and resubmit.

Best,
Swetlana Herbrandt

**Comment by infotroph** [comment]
I can reproduce this [on Travis](https://travis-ci.org/infotroph/forestr/jobs/339659650) but not yet on my own machine. Very puzzling.

**Comment by infotroph** [comment]
It's not finding the sample data! Passing an empty string to `process_pcl` produces exactly the same output CRAN got:

```
process_pcl("", marker.spacing = 10, user_height = 1.05,
+ max.vai = 8, pavd = FALSE, hist = FALSE)
how many in base df have NA
[1] 0
Transect Length
[1] -10
Error in `$<-.data.frame`(`*tmp*`, "sky_hit", value = TRUE) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former
```
